models/Productos.php
<?php

namespace app\models;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "productos".
 *
 * @property string $codigo
 * @property string $nombre
 * @property int $cantidad
 * @property int $precio
 */
class Productos extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'productos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['codigo', 'nombre', 'cantidad', 'precio'], 'required'],
            [['cantidad', 'precio'], 'integer'],
            [['codigo'], 'string', 'max' => 10],
            [['nombre'], 'string', 'max' => 20],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'codigo' => 'Codigo',
            'nombre' => 'Nombre',
            'cantidad' => 'Cantidad',
            'precio' => 'Precio',
        ];
    }


/*public static function getDB(){
return yii::$app->db;
}*/

  public function search($params)
    {
        $query = Productos::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'codigo' => $this->codigo,
            'precio' => $this->precio,
            "cantidad"=>$this->cantidad
        ]);

        $query->andFilterWhere(['like', 'nombre', $this->nombre]);

        return $dataProvider;
    }



}

controllers/ProductosController.php
<?php

namespace app\controllers;

use app\models\Productos;
use app\models\ValidarFormularioProducto;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\PaisSearch;
use app\models\ProductosSearch;
use yii\helpers\Html;
use yii\data\Pagination;
use yii\helpers\Url;

class ProductosController extends \yii\web\Controller
{
    public function actionIndex($mensaje=null)
    {
        return $this->render('index',["mensaje"=>$mensaje]);
    }


    public function actionFormulario($mensaje=null)
    {
    	return $this->render("formulario",["mensaje"=>$mensaje]);
    }


    public function actionRequest()
    {
    	$mensaje=null;
    	if(isset($_REQUEST["nombre"]))
    	{
    		$mensaje="Bien , primer formulario conectado con YII, enviaste: ".$_REQUEST["nombre"];
    	}

    	$this->redirect(["productos/formulario","mensaje"=>$mensaje]);

    }


   public function actionValidarformulario()
    {
    	$model= new ValidarFormulario;
    	if($model->load(Yii::$app->request->post()))
    		{
    			if ($model->validate()) {
    				//consultar en una BD ya q los datos fueron instroducidos correctamente
    			}
    			else{
    				$model->getErrors();
    			}
    		}
        return $this->render("validar",["model"=> $model]);
    }

public function actionProductos(){

  $model=new Productos;
  return $this->render("productos",["model"=>$model]);
}

public function actionCreate(){

    $model=new Productos;
    $mensaje=null;
  /*  if($model->load(yii::$app->request->post())){
        if($model->validate()){
            $table= new Productos;
            $table->codigo=$model->codigo;
            $table->nombre=$model->nombre;
            $table->cantidad=$model->cantidad;
            $table->precio=$model->precio;
            if ($table->insert()) {

                $mensaje="Datos guardados en la BD";
                $model->codigo=null;
                $model->nombre=null;
                $model->cantidad=null;
                $model->precio=null;
            }
            else{
                $mensaje="ha ocurrido un error";
            }
        }
    }*/
    if($model->load(yii::$app->request->post())){

        if($model->validate()) {
          $model->save();
           $mensaje="Datos guardados en la BD";
                $model->codigo=null;
                $model->nombre=null;
                $model->cantidad=null;
                $model->precio=null;
        
        $mensaje="GUARDADO CON EL METODO SAVE";}
      
    }


	return $this->render("create",["model"=>$model,"mensaje"=>$mensaje]);
}


/*public function actionVer(){
     $search=null;
    $table=new Productos;
    $model=$table->find()->all();

    $form=new ProductosSearch;
   
    if ($form->load(yii::$app->request->get())) {

        if($form->validate()){

            $search= Html::encode($form->q);
            $query=" SELECT*FROM productos WHERE codigo LIKE '%$search%' OR nombre LIKE '%$search%' ";
            $model=$table->findBySql($query)->all();
        }
        else {
            $form=getErrors();
        }
    }




    return $this->render("ver",["model"=>$model,"form"=>$form,"search"=>$search]);
}*/

public function actionVer(){

    $search=null;
    $form=new ProductosSearch;

    if ($form->load(yii::$app->request->get())){

        if ($form->validate()) {

              $search= Html::encode($form->q);
              $table= Productos::find()->where(["Like","codigo",$search])
              ->orWhere(["like","nombre",$search]);

              $count = clone $table;
              $pages= new Pagination(["pageSize"=>1,"totalCount"=>$count->count()]);


              $model= $table->offset($pages->offset)->limit($pages->limit)->all();
        } else {
            $form=getErrors();
        }
    }
    else{
        $table= Productos::find();
        $count= clone $table;

        $pages=new Pagination(["pageSize"=>1,"totalCount"=>$count->count()]);

           $model= $table->offset($pages->offset)->limit($pages->limit)->all();
    }

    return $this->render("ver",["model"=>$model,"form"=>$form,"search"=>$search,"pages"=>$pages]);
}


public function actionApi(){

  \yii::$app->response->format=\yii\web\Response::FORMAT_JSON;
   $table= Productos::find();

   return array('data'=>$table);

}


public function actionBuscar(){

    $form=new ProductosSearch;
    $search=null;
    if($form->load(yii::$app->request->get())){

        if($form->validate()){

            $search= Html::encode($form->q);
            $query="select*from productos where nombre like '%$search%' or codigo like '%$search%'";
            $form= $table->findBySql($query)->all();
        }
        else
        {
            $form=getErrors();
        }


    }

    return $this->render("ver",["form"=>$form,"$search"=>$search]);

}




  public function actionActualizar()
    {
       $model= new Productos;
       $mensaje=null;
       if ($model->load(yii::$app->request->post())) 
        {
           if ($model->validate())
            {
               $table=Productos::findOne($model->codigo);
               if ($table) 
               {

                    $table->nombre=$model->nombre;
                    $table->cantidad=$model->cantidad;
                    $table->precio=$model->precio;
                   if($table->update()){
                   $mensaje="Actualizado con el metodo update";}
                   else{
                    $mensaje="ni idea q mierda pasa";
                   }
               }
               else
               {
                $mensaje ="el Producto no ha sido encontrado";
               }

           }
           else
           {
            $model->getErrors();
           }
       }


       if (yii::$app->request->get("codigo")) {

          $codigo= Html::encode($_GET["codigo"]);

            $table= Productos::findOne($codigo);
            if($table){

                $model->codigo=$table->codigo;
                $model->nombre=$table->nombre;
                $model->cantidad=$table->cantidad;
                $model->precio=$table->precio;

            }
            else{
                return redirect(["productos/ver"]);
            }
       }
       else
       {
        return $this->redirect(["productos/ver"]);
       }

        return $this->render("actualizar",["model"=>$model,"mensaje"=>$mensaje]);
    }






    public function actionBorrar(){

        if(yii::$app->request->post()){

            $codigo= Html::encode($_POST["codigo"]);

            if(Productos::deleteAll("codigo=:codigo",[":codigo"=>$codigo])){

                 echo "eliminado , redireccionando ...";
                    echo "<meta http-equiv='refresh' content='3; ".Url::toRoute("productos/ver")."'>"; 


            }else{
                echo "Ha ocurrido un error al eliminar el producto, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='3; ".Url::toRoute("productos/ver")."'>"; 
            }

        }else{
            $this->redirect(["productos/ver"]);
        }


          
    }
















 protected function findModel($codigo)
    {
        if (($model = Productos::findOne($codigo)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.99');
    }

}

views/productos/actualizar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
$this->title = 'actualizar';
$this->params['breadcrumbs'][] = ['label' => 'Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<a href="<?= Url::toRoute("productos/ver") ?>">Ir a la lista de Productos</a>

<h1>Editar Producto con el codigo <?= Html::encode($_GET["codigo"]) ?></h1>

<h3><?= $mensaje ?></h3>

<?php $form = ActiveForm::begin([
    "method" => "post",
    'enableClientValidation' => true,
]);
?>



<div class="form-group">
 <?= $form->field($model, "codigo")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "nombre")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "cantidad")->input("number") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "precio")->input("number") ?>   
</div>

<?= Html::submitButton("Actualizar", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>

views/productos/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
$this->title = 'Registrar';
$this->params['breadcrumbs'][] = ['label' => 'Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<h2><a href="<?= Url::toRoute("productos/ver") ?>" >VER PRODUCTOS</a></h2>
<h1>Registrar Productos</h1>

<?php $form= ActiveForm::begin(["method"=>"post","enableClientValidation"=>true,]) ?>

<div class="form-group">

	<?= $form->field($model,"codigo")->input("text") ?>
	
</div>
<div class="form-group">

	<?= $form->field($model,"nombre")->input("text") ?>
	
</div>
<div class="form-group">

	<?= $form->field($model,"cantidad")->input("number") ?>
	
</div>
<div class="form-group">

	<?= $form->field($model,"precio")->input("number") ?>
	
</div>

<?= Html::submitButton("Enviar",["class"=> "btn btn-primary"])?>



<?php $form->end()?>
<h1><?= $mensaje ?></h1>

views/productos/formulario.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
?>

<h1>Formulario</h1>
<?= Html::beginForm(
	Url::toRoute("productos/request"), 
	"post", 
	["class"=> "form-inline"]);
?>
<div class="form-group">
	<?= Html::label("Ingresa tu Nombre","nombre")?>
	<?= Html::textInput("nombre",null,["class"=>"form-control"])?>
	</div>
	<?= Html::submitInput( "Enviar Nombre",["class"=> "btn btn-primary"])?>
	
	<h2><?= $mensaje ?></h2>

<?= Html::endForm()?>

views/productos/index.php
<h1>Vengo del update</h1>

views/productos/productos.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<div>
	<h1>TITULO</h1>
</div>


<?php $form = ActiveForm::begin(["method"=>"post",'enableClientValidation'=>true])  ?>



<div class="form-group">
	<?= $form->field($model,"codigo")->input("text") ?>
</div>
<div class="form-group">

	<?= $form->field($model,"nombre")->input("text")?>
</div>

<div class="form-group">
	<?= $form->field($model,"cantidad")->input("number") ?>
</div>

<div class="form-group">
	<?= $form->field($model,"precio")->input("number") ?>
</div>


	<?= Html::submitButton("Enviar" ,["class"=> "btn btn-primary"]) ?>



<?php $form->end();

views/productos/validar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h1>Validar Formulario</h1>

<?php $form= ActiveForm::begin(["method"=>"post","enableClientValidation"=>true,]) ?>

<div class="form-group">

	<?= $form->field($model,"codigo")->input("text") ?>
	
</div>
<div class="form-group">

	<?= $form->field($model,"nombre")->input("text") ?>
	
</div>
<div class="form-group">

	<?= $form->field($model,"cantidad")->input("number") ?>
	
</div>
<div class="form-group">

	<?= $form->field($model,"precio")->input("number") ?>
	
</div>

<?= Html::submitButton("Enviar",["class"=> "btn btn-primary"])?>



<?php $form->end()?>

views/productos/ver.php
<?php
use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\data\Pagination;
use yii\widgets\LinkPager;
$this->title = 'Ver';
$this->params['breadcrumbs'][] = ['label' => 'Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

 ?>

<h3>Buscar Producto</h3>
<?php $f= ActiveForm::begin(["method"=>"get","action"=> Url::toRoute("productos/ver"),"enableClientValidation"=>true,]) ?>
<div class="form-group">

	<?= $f->field($form,"q")->input("search") ?>
	
</div>
<?= Html::submitButton("Buscar",["class"=>"btn btn-primary"]) ?>


<?php $f->end()   ?>



 <h2><a href="<?= Url::toRoute("productos/create") ?>">Registrar un Producto   </a></h2>

 <h1>Lista de Productos</h1>

<table class="table table-bordered">
 <tr>
    <th>Codigo </th>
    <th>Nombre </th>
    <th>Cantidad </th>
    <th>Precio  </th>
    <th></th>
    <th></th>
 </tr>
<?php foreach ($model as $row): ?>
<tr>
    <td><?= $row->codigo ?></td>
    <td><?= $row->nombre ?></td>
    <td><?= $row->cantidad ?></td>
    <td><?= $row->precio ?></td>
    <td><a href="<?= Url::toRoute(["productos/actualizar","codigo"=>$row->codigo]) ?>">Editar</a></td>
    <td> 
        <a href="#" data-toggle="modal" data-target="#codigo_<?= $row->codigo ?>">Eliminar</a>
            <div class="modal fade" role="dialog" aria-hidden="true" id="codigo_<?= $row->codigo ?>">
                      <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                    <h4 class="modal-title">Eliminar Producto</h4>
                              </div>
                              <div class="modal-body">
                                    <p>¿Realmente deseas eliminar Producto con el codigo <?= $row->codigo ?>?</p>
                              </div>
                              <div class="modal-footer">
                              <?= Html::beginForm(Url::toRoute("productos/borrar"), "POST") ?>
                                    <input type="hidden" name="codigo" value="<?= $row->codigo ?>">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    <button type="submit" class="btn btn-primary">Eliminar</button>
                              <?= Html::endForm() ?>
                              </div>
                            </div><!-- /.modal-content -->
                      </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
    </td>
</tr>
<?php endforeach ?>

 </table>

 <h3><?=$search ?></h3>

 <?= LinkPager::widget(["pagination"=>$pages])?>